/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgiir.Vistas;

import imagenes.panelImagen;
import sgiir.statusBar;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import org.apache.commons.codec.digest.DigestUtils;
import sgiir.manejadorDB;
import sgiir.propiedades.propiedades;

/**
 *
 * @author Alfredo Mariño
 */
public class login extends javax.swing.JFrame {
    
    public ImageIcon imagenLogo = new ImageIcon(getClass().getResource("/imagenes/logo.png"));
    private propiedades msgFile = new propiedades();
    private String Query = "";
    private ResultSet rs;
    private String PassEncrypt = "";
    private String User = "";
    
    /*
    public String SystemUser = "";
    public String SystemPass = "";
    public String SystemPass = "";
    */
    
    //Manejador de base de datos
    manejadorDB DataBase = manejadorDB.getInstance();
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        if(!"".equals(DataBase.status)){
            statusBar.getInstance().setMsg(DataBase.status);
            btnIngresar.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldUsuario = new javax.swing.JTextField();
        fldContraseña = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        StatusBar = statusBar.getInstance();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        panelImagenLogo = new panelImagen(imagenLogo.getImage());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login SGIIR");
        setIconImage(imagenLogo.getImage());
        setLocation(new java.awt.Point(500, 250));
        setPreferredSize(new java.awt.Dimension(322, 265));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        fldUsuario.setText("master");
        fldUsuario.setToolTipText("");
        fldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fldUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fldUsuarioKeyReleased(evt);
            }
        });

        fldContraseña.setText("master");
        fldContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fldContraseñaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fldContraseñaKeyReleased(evt);
            }
        });

        btnIngresar.setText(msgFile.getProperty("lbl0001"));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        StatusBar.setPreferredSize(new java.awt.Dimension(64, 14));

        lblUsuario.setText(msgFile.getProperty("lbl0002"));

        lblContraseña.setText(msgFile.getProperty("lbl0003"));

        javax.swing.GroupLayout panelImagenLogoLayout = new javax.swing.GroupLayout(panelImagenLogo);
        panelImagenLogo.setLayout(panelImagenLogoLayout);
        panelImagenLogoLayout.setHorizontalGroup(
            panelImagenLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImagenLogoLayout.setVerticalGroup(
            panelImagenLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatusBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fldContraseña)
                            .addComponent(fldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(panelImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valida(){
        User = fldUsuario.getText().toUpperCase();
        PassEncrypt = Encrypt(fldContraseña.getText().toUpperCase());
        
        if(!"".equals(User)){
            try {
              
                Query = "Select * from autenticacion where PassAutenticacion = '" + PassEncrypt
                        + "' and UserAutenticacion = '" + User + "'";
                
                rs = DataBase.executeQuery(Query);
                
                //comprueba que existe un registro
                if(rs.absolute(1)){
                    
                    //oculta esta pantalla
                    this.setVisible(false);
                    
                    //envia parametros y muestra Menu
                    frameMenu VistaMenu = new frameMenu(rs.getInt("CodigoPersona"), rs.getByte("nivelAutenticacion"));
                    VistaMenu.setVisible(true);
                    
                }else{
                    statusBar.getInstance().setMsg(msgFile.getProperty("msg0001"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{

            statusBar.getInstance().setMsg(msgFile.getProperty("msg0001"));
        }
    }
    
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        valida();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
    }//GEN-LAST:event_formKeyReleased

    private void fldContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldContraseñaKeyPressed
    }//GEN-LAST:event_fldContraseñaKeyPressed

    private void fldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldUsuarioKeyPressed
    }//GEN-LAST:event_fldUsuarioKeyPressed

    private void fldUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldUsuarioKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            valida();
        }
    }//GEN-LAST:event_fldUsuarioKeyReleased

    private void fldContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldContraseñaKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            valida();
        }
    }//GEN-LAST:event_fldContraseñaKeyReleased
    
    //Encripta texto como la contraseña
    private static String Encrypt(String texto){
      
        return DigestUtils.md5Hex(texto); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StatusBar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPasswordField fldContraseña;
    private javax.swing.JTextField fldUsuario;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelImagenLogo;
    // End of variables declaration//GEN-END:variables
}

                /*
                //DataBase.metaDatos();
                //DataBase.insertData("autenticacion", "AAMV", "", "2", "2");
                Query = "Update autenticacion set PassAutenticacion = '" + Encrypt(fldContraseña.getText())
                +"' where UserAutenticacion = '" + fldUsuario.getText() + "'";
                //Query = "Update autenticacion set PassAutenticacion = 'hola' where UserAutenticacion = 'AAMV'";
                DataBase.executeUpdate(Query);
                */
